version: 2

models:
  - name: dim_vendors
    description: "Dimension table for taxi vendors."

  - name: dim_zones
    description: "Dimension table for taxi zones in New York City."

  - name: fct_trips
    description: "Fact table for taxi trips in New York City."
    